### PR TITLE
Material tabs

### PR DESCRIPTION
**Pull request by mustafa01ali**
Replaced TabWidget with customized sliding tabs (#662), removed holo-style headers

Screenshots - http://imgur.com/TWDqTQO,QsE21M9

### CODE REVIEW

**Comment by fadils** [comment]
Looks good.
I'm not sure about the tab indicator style/color though. It just doesn't have good contrast to the view below it IMHO.

**Comment by mustafa01ali** [comment]
@fadils I see what you are saying. I've increase the elevation to have a bigger shadow.

device-2015-01-08-075029


Is this better or you think we should change the selected indicator color?

**Comment by mustafa01ali** [comment]
Here's another option

device-2015-01-08-091435

**Comment by atermenji** [comment]
Increased elevation looks better than blue indicator color IMHO.
Indicator color has good contrast with tab backgroung (white vs dark) while elevation shadow adds additional diversity between tabs and content

**Comment by mustafa01ali** [comment]
@atermenji I agree. Since elevation is not supported on older versions, I've implemented a generic solution that looks the same. Curious to know what @fadils thinks.

**Comment by fadils** [comment]
@mustafa01ali, same with @atermenji, I don't really like the blue indicator either.

But, I was thinking about creating a clear separation with a good contrast about this. 
Then, I came up with this.

screenshot_2015-01-09-06-53-29

Well, I guess now we have options.

**Comment by atermenji** [comment]
@fadils personally, I think that elevation and shadow is mostly used in cases like this.

Let me explain my thoughts:
Since the tab background has deep dark color, tab text and indicator need to have contrast and white color fits the best. On the other side main content has also white background.
From what I've seen so far in other apps, they use 2 options in this case:
* Fill indicator with a different, third color, like red or blue or something else which finds place in other places of an app. Like 1 of 3 main app colors
* Place shadow/elevation below, like @mustafa01ali  did

Anyway, I'm not a regular UX/UI designer, so I can not provide the best option and this is a thing of discussion.
Do you have some examples from other apps with bottom padding for indicators?

**Comment by atermenji** [comment]
as an example here is a screenshot from my Contacts app:
image

As you can see, it has almost the same case as ours, and it has a shadow elevation. 

Indicator height is also smaller there but I'm not certain if it is a must in latest guidelines.

**Comment by fadils** [comment]
@atermenji Thanks for your elaboration. I was just voicing another option, which in my personal opinion is better than shadow.

Looking at how other apps do it, I guess shadow is the way to go. =)
I'm not a regular UX designer too, so this is up for discussion.

My inspiration to get to that option:
screenshot_2015-01-09-08-10-10

However, when it's scrolled up, then it uses shadow, which is closer to what @mustafa01ali did and what you suggested earlier:
screenshot_2015-01-09-08-15-18

**Comment by mustafa01ali** [comment]
@atermenji @fadils Good discussion, this was my inspiration while implementing the tabs - 

device-2015-01-08-201443

So if you guys agree on the white indicator with shadow, we can merge this PR as it has that implementation.

**Pull request merged**
