### PR TITLE
Fixed #575 and some in #84

### LINKED ISSUE #575: Can't close tickets I opened
When I look at tickets on my own repositories I can close them using the menu. But on a ticket I opened on somebody else's  repository, I don't have the menu item to close the issue in the app. On the web, I can close the issue because I opened it.

### PR DESCRIPTION
**Pull request by Meisolsson**
Comments now only shows menu if needed
Gist options menu now updates correctly

### CODE REVIEW

**Comment by fadils** [comment]
@jonanp for any additional comments..

**Comment by jonanp** [comment]
I'm away this week and wont be able to look into any PR until the weekend. So if it's an urgent bugfix, merge it if you wish.

**Comment by Meisolsson** [comment]
It's not urgent and it would be better if it was tested by more people than me

**Comment by fadils** [comment]
LGTM. Thanks!

**Pull request merged**
