### PR TITLE
Fixed zooming in code view

### PR DESCRIPTION
**Pull request by Meisolsson**
also fixed Toolbar not showing in code view

### CODE REVIEW

**Comment by keyeechen** [comment]
I hope this can better the user experience.

**Comment by fadils** [comment]
Same thing here @Meisolsson, commit message should be without the dash. Could you please amend it?

**Comment by fadils** [comment]
Merged

**Comment by Parker8283** [comment]
This restores half of the functionality of the version on the store right now, but I was able to also zoom out past the default size, and I cannot do that with this new PR. I can zoom in just fine.

**Comment by Meisolsson** [comment]
Looked at it and found a fix, will look into it more tomorrow

**Comment by Parker8283** [comment]
Any news on the fix? Or did I miss that you've already committed it?

**Pull request closed without merging**
