### PR TITLE
add left sliding back

### PR DESCRIPTION
**Pull request by zhengxiaopeng**
add left sliding back, left sliding in entire screen(extends BaseActivity) or in left edge(extends DialogFragmentActivity)  
my github/android repo https://github.com/zhengxiaopeng/android   
sample

### CODE REVIEW

**Comment by jonanp** [comment]
I'm not sure I like this feature, as the app uses the horizontal scroll everywhere. But I'll install it on my phone and give it a try before deciding.

**Comment by zhengxiaopeng** [comment]
@jonanp   If the app requires horizontal slide you can only use the edge of the slide returned. Easy to use sliding returned if needn‘t horizontal scroll , but looks like the kind of place too little. : (

**Comment by hzsweers** [comment]
I'm not really a fan of this as well, if even only because of the animation. Intuition tells me that sliding something away should result in some sort of translation out of the view.

**Comment by fadils** [comment]
Good point

**Comment by zhengxiaopeng** [comment]
If need to, then you can add it to setting.

**Comment by jonanp** [comment]
I've been trying this feature on my phone for a few days and I haven't had a good experience. I've closed a few activities accidentaly, which is very frustraiting, and a lot of times I really wanted to close the activity I've had to do the gesture 3 or 4 times because the horizontal scroll was taking the focus.

**Pull request closed without merging**
