### PR TITLE
translation update

### PR DESCRIPTION
**Pull request by danielFerecatu**
- added translation for deleting repo
- missing diacritics
- spelling

### CODE REVIEW

**Comment by danielFerecatu** [comment]
@fadils why isn't this pull request merged?

**Comment by fadils** [comment]
@danielFerecatu Hey, can you please squash the commits? After that, it should be good.

**Comment by danielFerecatu** [comment]
Is this the right way or i should fork it again and then open the PR?

**Comment by fadils** [comment]
no need. You can just update this exact PR.

**Comment by danielFerecatu** [comment]
ok, i did that here: https://github.com/danielFerecatu/android/commit/cccf6c3242078f64cac8bdfc7718c977a91c166f

**Comment by jonan** [comment]
Now this PR has 5 commits, the 2 initial commits, 2 reverts and the final commit. You should only have the last one.

**Comment by danielFerecatu** [comment]
yes, but how can i do that?

**Comment by jonan** [comment]
Easiest way is probably:
`git reset --hard HEAD~5`
`git cherry-pick cccf6c3`
`git push -f origin master`

**Comment by danielFerecatu** [comment]
thanks, it worked :)

**Comment by danielFerecatu** [comment]
@fadils could you merge this?

**Comment by fadils** [comment]
Thanks @danielFerecatu!

**Pull request merged**
